change_amount=float(input())
change_amount_coins=change_amount*100
coin_counter=0
two_lev_counter=0
one_lev_counter=0
fifty_stotinki_counter=0
twenty_stotinki_counter=0
ten_stotinki_counter=0
five_stotinki_counter=0
two_stotinki_counter=0
one_stotinki_counter=0

while change_amount_coins>=200:
    coin_counter+=1
    two_lev_counter+=1
    change_amount_coins-=200
while change_amount_coins>=100:
    coin_counter+=1
    one_lev_counter+=1
    change_amount_coins-=100
while change_amount_coins>=50:
    coin_counter+=1
    fifty_stotinki_counter+=1
    change_amount_coins-=50
while change_amount_coins>=20:
    coin_counter+=1
    twenty_stotinki_counter+=1
    change_amount_coins-=20
while change_amount_coins>=10:
    coin_counter+=1
    ten_stotinki_counter+=1
    change_amount_coins-=10
while change_amount_coins>=5:
    coin_counter+=1
    five_stotinki_counter+=1
    change_amount_coins-=5
while change_amount_coins>=2:
    coin_counter+=1
    two_stotinki_counter+=1
    change_amount_coins-=2
while change_amount_coins>=1:
    coin_counter+=1
    one_stotinki_counter+=1
    change_amount_coins-=1
print(f"{coin_counter}")